### ISSUE TITLE
Create buildJoinString() Method

### ISSUE THREAD

**Issue by iatenine** [iatenine/ORM_linram_p1#18]
String buildJoinString(String tableName1, String tableName2, String[] colNames) - Return a string of "SELECT {colNames} FROM tableName1 JOIN tableName2;" (or whatever the proper syntax for a join is)

**Comment by ramirez45** [comment]
String buildJoinString(String tableName1, String tableName2, String[] colNames) - Return a ResultSet of "SELECT {colNames} FROM tableName1 JOIN tableName2;" (or whatever the proper syntax for a join is)
Method now returns a ResultSet instead of a String
